addons:
  apt:
    packages:
    - pass
    - gnupg

language: go

go_import_path: gopkg.in/Netflix-Skunkworks/go-jira.v1

go:
  - 1.12.x

script:
  - go test ./...
  - go vet -composites=false ./...
  - make
  - make prove 2>&1
